#!/bin/bash
set -v
java Variance 2 4 6 8 10
java Variance 1 3 5 7 9
java Variance 4 6
java Variance 3 9 6
java Variance 4 16 64 256
java Variance 10 10 10 10 10
java Variance 10 10 10 11 10
java Variance 7 6 5 4 3 2 1
java Variance 1
java Variance 100 -416 -2 908
java Variance -4 -72 -6 -15 -3



