/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.ibmsdrh;

import java.awt.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author mbax2mh2
 */
public class ibmsdrhUI extends javax.swing.JFrame {
    
    /**
     * Add state members
     */
    private Date startHoliday = null;
    private Date endHoliday = null;
    private int driverID;
    private Object[][] RosterData = null;

    /**
     * Creates new form ibmsdrhUI
     */
    public ibmsdrhUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MessageOptionPane = new javax.swing.JOptionPane();
        RosterTableModel = new my.ibmsdrh.RosterTableModel();
        jPanel1 = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        OptionsPanel = new javax.swing.JPanel();
        ProduceRosterButton = new javax.swing.JButton();
        ViewLiveDeparturesButton = new javax.swing.JButton();
        JourneyPlannerButton = new javax.swing.JButton();
        RequestHolidayButton = new javax.swing.JButton();
        ViewRosterButton = new javax.swing.JButton();
        LoginPanel = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        LoginField = new javax.swing.JTextField();
        LoginButtonsPanel = new javax.swing.JPanel();
        LoginSubmit = new javax.swing.JButton();
        LoginCancel = new javax.swing.JButton();
        DatesPanel = new javax.swing.JPanel();
        StartDateLabel = new javax.swing.JLabel();
        StartDatePicker = new org.jdesktop.swingx.JXDatePicker();
        EndDateLabel = new javax.swing.JLabel();
        EndDatePicker = new org.jdesktop.swingx.JXDatePicker();
        SubmitRequestButton = new javax.swing.JButton();
        CancelRequestButton = new javax.swing.JButton();
        ResponsePanel = new javax.swing.JPanel();
        ResponseScrollPane = new javax.swing.JScrollPane();
        ResponseTextArea = new javax.swing.JTextArea();
        ResponseButtonsPanel = new javax.swing.JPanel();
        ResponseAcceptButton = new javax.swing.JButton();
        ResponseDeclineButton = new javax.swing.JButton();
        RosterPanel = new javax.swing.JPanel();
        RosterScrollPane = new javax.swing.JScrollPane();
        RosterTextArea = new javax.swing.JTextArea();
        LiveDeparturesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        JourneyPlannerPanel = new javax.swing.JPanel();
        FromAreaLabel = new javax.swing.JLabel();
        String[] routes = {"382", "386"};
        StartingAreaCombo = new javax.swing.JComboBox();
        FromBusStopLabel = new javax.swing.JLabel();
        StartingStopCombo = new javax.swing.JComboBox();
        ToAreaLabel = new javax.swing.JLabel();
        DestinationAreaCombo = new javax.swing.JComboBox();
        ToBusStopLabel = new javax.swing.JLabel();
        DestinationStopCombo = new javax.swing.JComboBox();
        DateLabel = new javax.swing.JLabel();
        JourneyDatePicker = new org.jdesktop.swingx.JXDatePicker();
        StartTimeLabel = new javax.swing.JLabel();
        GenerateRoutesButton = new javax.swing.JButton();
        SelectHourCombo = new javax.swing.JComboBox();
        SelectMinuteCombo = new javax.swing.JComboBox();
        BackToMenuButton = new javax.swing.JButton();
        JouneyResultsPannel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PlannerBackButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        JourneyBackButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        MenuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("What would you like to do?"));
        MenuPanel.setMaximumSize(new java.awt.Dimension(300, 100));
        MenuPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        MenuPanel.setLayout(new java.awt.CardLayout(10, 10));

        OptionsPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        ProduceRosterButton.setText("Produce Roster");
        OptionsPanel.add(ProduceRosterButton);

        ViewLiveDeparturesButton.setText("View Live Departures");
        ViewLiveDeparturesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewLiveDeparturesButtonActionPerformed(evt);
            }
        });
        OptionsPanel.add(ViewLiveDeparturesButton);

        JourneyPlannerButton.setText("Journey Planner");
        JourneyPlannerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JourneyPlannerButtonActionPerformed(evt);
            }
        });
        OptionsPanel.add(JourneyPlannerButton);

        RequestHolidayButton.setText("Request Holiday");
        RequestHolidayButton.setMaximumSize(new java.awt.Dimension(300, 27));
        RequestHolidayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestHolidayButtonActionPerformed(evt);
            }
        });
        OptionsPanel.add(RequestHolidayButton);

        ViewRosterButton.setText("Generate Roster");
        ViewRosterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRosterButtonActionPerformed(evt);
            }
        });
        OptionsPanel.add(ViewRosterButton);

        MenuPanel.add(OptionsPanel, "card2");

        LoginPanel.setLayout(new java.awt.GridLayout(3, 0, 0, 100));

        LoginLabel.setText("Please enter your driver number below:");
        LoginPanel.add(LoginLabel);
        LoginPanel.add(LoginField);

        LoginButtonsPanel.setLayout(new java.awt.GridLayout(0, 2, 100, 0));

        LoginSubmit.setText("Submit");
        LoginSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginSubmitActionPerformed(evt);
            }
        });
        LoginButtonsPanel.add(LoginSubmit);

        LoginCancel.setText("Cancel");
        LoginCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginCancelActionPerformed(evt);
            }
        });
        LoginButtonsPanel.add(LoginCancel);

        LoginPanel.add(LoginButtonsPanel);

        MenuPanel.add(LoginPanel, "card5");

        DatesPanel.setLayout(new java.awt.GridLayout(0, 2, 100, 20));

        StartDateLabel.setText("Start Date");
        DatesPanel.add(StartDateLabel);

        StartDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartDatePickerActionPerformed(evt);
            }
        });
        DatesPanel.add(StartDatePicker);

        EndDateLabel.setText("End Date");
        DatesPanel.add(EndDateLabel);
        DatesPanel.add(EndDatePicker);

        SubmitRequestButton.setText("Submit");
        SubmitRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitRequestButtonActionPerformed(evt);
            }
        });
        DatesPanel.add(SubmitRequestButton);

        CancelRequestButton.setText("Cancel");
        CancelRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelRequestButtonActionPerformed(evt);
            }
        });
        DatesPanel.add(CancelRequestButton);

        MenuPanel.add(DatesPanel, "card3");

        ResponsePanel.setLayout(new java.awt.GridLayout(2, 0));

        ResponseTextArea.setEditable(false);
        ResponseTextArea.setColumns(20);
        ResponseTextArea.setRows(5);
        ResponseScrollPane.setViewportView(ResponseTextArea);

        ResponsePanel.add(ResponseScrollPane);

        ResponseButtonsPanel.setLayout(new java.awt.GridLayout(1, 0, 100, 0));

        ResponseAcceptButton.setText("Accept");
        ResponseAcceptButton.setEnabled(false);
        ResponseAcceptButton.setPreferredSize(new java.awt.Dimension(100, 50));
        ResponseAcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResponseAcceptButtonActionPerformed(evt);
            }
        });
        ResponseButtonsPanel.add(ResponseAcceptButton);

        ResponseDeclineButton.setText("Decline");
        ResponseDeclineButton.setPreferredSize(new java.awt.Dimension(100, 50));
        ResponseDeclineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResponseDeclineButtonActionPerformed(evt);
            }
        });
        ResponseButtonsPanel.add(ResponseDeclineButton);

        ResponsePanel.add(ResponseButtonsPanel);

        MenuPanel.add(ResponsePanel, "card4");

        RosterTextArea.setColumns(20);
        RosterTextArea.setRows(5);
        RosterScrollPane.setViewportView(RosterTextArea);

        javax.swing.GroupLayout RosterPanelLayout = new javax.swing.GroupLayout(RosterPanel);
        RosterPanel.setLayout(RosterPanelLayout);
        RosterPanelLayout.setHorizontalGroup(
            RosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RosterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );
        RosterPanelLayout.setVerticalGroup(
            RosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RosterPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(RosterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
        );

        MenuPanel.add(RosterPanel, "card6");

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout LiveDeparturesPanelLayout = new javax.swing.GroupLayout(LiveDeparturesPanel);
        LiveDeparturesPanel.setLayout(LiveDeparturesPanelLayout);
        LiveDeparturesPanelLayout.setHorizontalGroup(
            LiveDeparturesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LiveDeparturesPanelLayout.createSequentialGroup()
                .addGroup(LiveDeparturesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LiveDeparturesPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1))
                    .addGroup(LiveDeparturesPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(157, 157, 157)
                .addGroup(LiveDeparturesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        LiveDeparturesPanelLayout.setVerticalGroup(
            LiveDeparturesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LiveDeparturesPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(LiveDeparturesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(LiveDeparturesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(762, Short.MAX_VALUE))
        );

        MenuPanel.add(LiveDeparturesPanel, "card9");

        FromAreaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FromAreaLabel.setText("From Area:");

        StartingAreaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartingAreaComboActionPerformed(evt);
            }
        });

        FromBusStopLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FromBusStopLabel.setText("From Bus Stop:");

        ToAreaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ToAreaLabel.setText("To Area:");

        ToBusStopLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ToBusStopLabel.setText("To Bus Stop:");

        DateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DateLabel.setText("Start Date:");

        JourneyDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JourneyDatePickerActionPerformed(evt);
            }
        });

        StartTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StartTimeLabel.setText("Start Time:");

        GenerateRoutesButton.setText("Show Available Routes");
        GenerateRoutesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateRoutesButtonActionPerformed(evt);
            }
        });

        SelectHourCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "12", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        SelectHourCombo.setToolTipText("Select Hour");
        SelectHourCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectHourComboActionPerformed(evt);
            }
        });

        SelectMinuteCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        SelectMinuteCombo.setToolTipText("Select Minute");
        SelectMinuteCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectMinuteComboActionPerformed(evt);
            }
        });

        BackToMenuButton.setText("Back to Menu");
        BackToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JourneyPlannerPanelLayout = new javax.swing.GroupLayout(JourneyPlannerPanel);
        JourneyPlannerPanel.setLayout(JourneyPlannerPanelLayout);
        JourneyPlannerPanelLayout.setHorizontalGroup(
            JourneyPlannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JourneyPlannerPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(JourneyPlannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ToAreaLabel)
                    .addComponent(FromAreaLabel)
                    .addComponent(DateLabel)
                    .addComponent(DestinationAreaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JourneyDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(StartingAreaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(JourneyPlannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JourneyPlannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(DestinationStopCombo, 0, 200, Short.MAX_VALUE)
                        .addComponent(ToBusStopLabel)
                        .addComponent(StartingStopCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JourneyPlannerPanelLayout.createSequentialGroup()
                            .addGroup(JourneyPlannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SelectHourCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StartTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(19, 19, 19)
                            .addComponent(SelectMinuteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(FromBusStopLabel))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JourneyPlannerPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(BackToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(GenerateRoutesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        JourneyPlannerPanelLayout.setVerticalGroup(
            JourneyPlannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JourneyPlannerPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(JourneyPlannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FromAreaLabel)
                    .addComponent(FromBusStopLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JourneyPlannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartingAreaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartingStopCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(JourneyPlannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToAreaLabel)
                    .addComponent(ToBusStopLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JourneyPlannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DestinationStopCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DestinationAreaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(JourneyPlannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateLabel)
                    .addComponent(StartTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JourneyPlannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JourneyDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectHourCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectMinuteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 474, Short.MAX_VALUE)
                .addGroup(JourneyPlannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GenerateRoutesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(BackToMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );

        MenuPanel.add(JourneyPlannerPanel, "card8");
        JourneyPlannerPanel.getAccessibleContext().setAccessibleName("");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setToolTipText("");
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel6.setText("Arrival Time:");

        jLabel7.setText("Journey Duration:");

        jLabel8.setText("Bus Swaps:");

        jLabel3.setText("Service Number:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(326, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jLabel6)
                    .addGap(73, 73, 73)
                    .addComponent(jLabel7)
                    .addGap(58, 58, 58)
                    .addComponent(jLabel8)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addContainerGap(43, Short.MAX_VALUE)))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });

        jLabel9.setText("Arrival Time:");

        jLabel10.setText("Journey Duration:");

        jLabel11.setText("Bus Swaps:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jLabel9)
                    .addGap(73, 73, 73)
                    .addComponent(jLabel10)
                    .addGap(58, 58, 58)
                    .addComponent(jLabel11)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11))
                    .addContainerGap(43, Short.MAX_VALUE)))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jLabel12.setText("Arrival Time:");

        jLabel13.setText("Journey Duration:");

        jLabel14.setText("Bus Swaps:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jLabel12)
                    .addGap(73, 73, 73)
                    .addComponent(jLabel13)
                    .addGap(58, 58, 58)
                    .addComponent(jLabel14)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14))
                    .addContainerGap(43, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 195, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(571, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel6);

        PlannerBackButton.setText("Back to Planner");
        PlannerBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlannerBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JouneyResultsPannelLayout = new javax.swing.GroupLayout(JouneyResultsPannel);
        JouneyResultsPannel.setLayout(JouneyResultsPannelLayout);
        JouneyResultsPannelLayout.setHorizontalGroup(
            JouneyResultsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JouneyResultsPannelLayout.createSequentialGroup()
                .addGroup(JouneyResultsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JouneyResultsPannelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JouneyResultsPannelLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(PlannerBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        JouneyResultsPannelLayout.setVerticalGroup(
            JouneyResultsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JouneyResultsPannelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(PlannerBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        MenuPanel.add(JouneyResultsPannel, "card9");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Ride for 20 minutes.\n1: Swap to service 303 at bus stop [bus stop]\nRide for 30 minutes\n2: Swap to service 149 at bus stop [2nd bus stop]\nRide for 6 seconds\nYou have arrived at [your destination]\n");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Swap Details:");

        JourneyBackButton.setText("Back to Journey List");
        JourneyBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JourneyBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(JourneyBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(JourneyBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(439, Short.MAX_VALUE))
        );

        MenuPanel.add(jPanel2, "card10");

        getContentPane().add(MenuPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RequestHolidayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestHolidayButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(MenuPanel.getLayout());
        cl.next(MenuPanel);
    }//GEN-LAST:event_RequestHolidayButtonActionPerformed

    private void CancelRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelRequestButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(MenuPanel.getLayout());
        cl.show(MenuPanel, "card2");
    }//GEN-LAST:event_CancelRequestButtonActionPerformed

    private void SubmitRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitRequestButtonActionPerformed
        // TODO add your handling code here:
        startHoliday = StartDatePicker.getDate();
        endHoliday = EndDatePicker.getDate();
        
        Date minStart = new Date();
        minStart.setDate(minStart.getDate() + 6);
        
        String response = "";
        
        if(startHoliday == null) {
            JOptionPane.showMessageDialog(this, "Please specify a start date",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(endHoliday == null) {
            JOptionPane.showMessageDialog(this, "Please specify an end date",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(startHoliday.after(endHoliday)) {
            JOptionPane.showMessageDialog(this, "End date must be after start date",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(startHoliday.before(minStart)) {
            JOptionPane.showMessageDialog(this, "Start date must be at least 7 days from now",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(!DriverController.hasHolidaysLeft(driverID, startHoliday, endHoliday)) {
            JOptionPane.showMessageDialog(this, "You only have " + DriverController.getHolidaysLeft(driverID) +
                    " left",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ArrayList<Date> unavailableDates = DriverController.getUnavailableDates(startHoliday, endHoliday);
        
        if(unavailableDates.isEmpty()) {
            ResponseTextArea.setText("");
            ResponseTextArea.setText("safe");
            ResponseAcceptButton.setEnabled(true);
        }
        else {
            ResponseTextArea.setText("");
            response += "The following dates are unavailable: " + '\n';
            
            for(Date d : unavailableDates) {
                response += d.toString() + '\n';
            }
            
            ResponseTextArea.setText(response);
            ResponseAcceptButton.setEnabled(false);
        }
         
      
        
        CardLayout cl = (CardLayout)(MenuPanel.getLayout());
        cl.next(MenuPanel);
    }//GEN-LAST:event_SubmitRequestButtonActionPerformed

    private void StartDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartDatePickerActionPerformed

    private void ResponseDeclineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResponseDeclineButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(MenuPanel.getLayout());
        cl.show(MenuPanel, "card2");
    }//GEN-LAST:event_ResponseDeclineButtonActionPerformed

    private void ResponseAcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResponseAcceptButtonActionPerformed
        // TODO add your handling code here:
        DriverController.setOnHoliday(driverID, startHoliday, endHoliday);
        JOptionPane.showMessageDialog(this, "Dates inserted",
                "Complete",
                JOptionPane.INFORMATION_MESSAGE);
        CardLayout cl = (CardLayout)(MenuPanel.getLayout());
        cl.previous(MenuPanel);
        
    }//GEN-LAST:event_ResponseAcceptButtonActionPerformed

    private void LoginCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginCancelActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(MenuPanel.getLayout());
        cl.show(MenuPanel, "card2");
    }//GEN-LAST:event_LoginCancelActionPerformed

    private void LoginSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginSubmitActionPerformed
        // TODO add your handling code here:
        String input = LoginField.getText();
        
        if(input.compareTo("") == 0) {
            JOptionPane.showMessageDialog(this, "Please enter your driver number",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
        driverID = Integer.parseInt(input);
        }
        catch (NumberFormatException exception) {
            JOptionPane.showMessageDialog(this, "Your driver number must contain only digits",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        driverID = DriverController.findDriver(input);
        if(driverID == 0){
            JOptionPane.showMessageDialog(this, "Please enter your driver number again",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
            
                
        System.out.println(driverID);
        
        CardLayout cl = (CardLayout)(MenuPanel.getLayout());
        cl.next(MenuPanel);
    }//GEN-LAST:event_LoginSubmitActionPerformed

    private void ViewRosterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRosterButtonActionPerformed
        // TODO add your handling code here:
        Roster.main();
        RosterTextArea.setText(Roster.str);
        CardLayout cl = (CardLayout)(MenuPanel.getLayout());
        cl.show(MenuPanel, "card6");
    }//GEN-LAST:event_ViewRosterButtonActionPerformed

    private void ViewLiveDeparturesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewLiveDeparturesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewLiveDeparturesButtonActionPerformed

    private void JourneyDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JourneyDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JourneyDatePickerActionPerformed

    private void GenerateRoutesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateRoutesButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(MenuPanel.getLayout());
        cl.show(MenuPanel, "card9");
    }//GEN-LAST:event_GenerateRoutesButtonActionPerformed

    private void StartingAreaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartingAreaComboActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_StartingAreaComboActionPerformed

    private void JourneyPlannerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JourneyPlannerButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(MenuPanel.getLayout());
        cl.show(MenuPanel, "card8");
        
        String[] poo = {"poo"}; 
        StartingAreaCombo.setModel(new javax.swing.DefaultComboBoxModel(poo));
        StartingStopCombo.setModel(new javax.swing.DefaultComboBoxModel(poo));
        DestinationStopCombo.setModel(new javax.swing.DefaultComboBoxModel(poo));
        DestinationAreaCombo.setModel(new javax.swing.DefaultComboBoxModel(poo));
        
        ArrayList<String> areaNames = new ArrayList<String>();
        ArrayList<String> stopNames = new ArrayList<String>();
        
        //Get Bus Stops
        int[] routes = BusStopInfo.getRoutes();
        for(int i = 0; i < routes.length; i++) {
            int[] stops = BusStopInfo.getBusStops(routes[i]);
            
            for(int j = 0; j < stops.length; j++)
                stopNames.add(BusStopInfo.getFullName(stops[j]));
        }
         
        int[] areas = BusStopInfo.getAreas();
        
        //Get Areas
        for (int i = 0; i < areas.length; i++){
            areaNames.add(BusStopInfo.getAreaName(areas[i]));
        }
    
        //Get rid of duplicates
        HashSet<String> hashSet = new HashSet<String>();
        hashSet.addAll(stopNames);
        stopNames.clear();
        stopNames.addAll(hashSet);
        
        hashSet.clear();
        hashSet.addAll(areaNames);
        areaNames.clear();
        areaNames.addAll(hashSet);
    
        String[] busStops = new String[stopNames.size()];
        busStops = stopNames.toArray(busStops);
        StartingStopCombo.setModel(new javax.swing.DefaultComboBoxModel(busStops));
        DestinationStopCombo.setModel(new javax.swing.DefaultComboBoxModel(busStops));
        
        String[] stopAreas = new String[areaNames.size()];
        stopAreas = areaNames.toArray(stopAreas);
        StartingAreaCombo.setModel(new javax.swing.DefaultComboBoxModel(stopAreas));
        DestinationAreaCombo.setModel(new javax.swing.DefaultComboBoxModel(stopAreas));
              
        
    }//GEN-LAST:event_JourneyPlannerButtonActionPerformed

    private void SelectMinuteComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectMinuteComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectMinuteComboActionPerformed

    private void SelectHourComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectHourComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectHourComboActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(MenuPanel.getLayout());
        cl.show(MenuPanel, "card10");
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
         CardLayout cl = (CardLayout)(MenuPanel.getLayout());
         cl.show(MenuPanel, "card10");
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:
         CardLayout cl = (CardLayout)(MenuPanel.getLayout());
         cl.show(MenuPanel, "card10");
    }//GEN-LAST:event_jPanel10MouseClicked

    private void JourneyBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JourneyBackButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(MenuPanel.getLayout());
        cl.show(MenuPanel, "card9");
    }//GEN-LAST:event_JourneyBackButtonActionPerformed

    private void PlannerBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlannerBackButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(MenuPanel.getLayout());
        cl.show(MenuPanel, "card8");
    }//GEN-LAST:event_PlannerBackButtonActionPerformed

    private void BackToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(MenuPanel.getLayout());
        cl.show(MenuPanel, "card2");
    }//GEN-LAST:event_BackToMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ibmsdrhUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ibmsdrhUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ibmsdrhUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ibmsdrhUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        database.openBusDatabase();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ibmsdrhUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToMenuButton;
    private javax.swing.JButton CancelRequestButton;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JPanel DatesPanel;
    private javax.swing.JComboBox DestinationAreaCombo;
    private javax.swing.JComboBox DestinationStopCombo;
    private javax.swing.JLabel EndDateLabel;
    private org.jdesktop.swingx.JXDatePicker EndDatePicker;
    private javax.swing.JLabel FromAreaLabel;
    private javax.swing.JLabel FromBusStopLabel;
    private javax.swing.JButton GenerateRoutesButton;
    private javax.swing.JPanel JouneyResultsPannel;
    private javax.swing.JButton JourneyBackButton;
    private org.jdesktop.swingx.JXDatePicker JourneyDatePicker;
    private javax.swing.JButton JourneyPlannerButton;
    private javax.swing.JPanel JourneyPlannerPanel;
    private javax.swing.JPanel LiveDeparturesPanel;
    private javax.swing.JPanel LoginButtonsPanel;
    private javax.swing.JButton LoginCancel;
    private javax.swing.JTextField LoginField;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton LoginSubmit;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JOptionPane MessageOptionPane;
    private javax.swing.JPanel OptionsPanel;
    private javax.swing.JButton PlannerBackButton;
    private javax.swing.JButton ProduceRosterButton;
    private javax.swing.JButton RequestHolidayButton;
    private javax.swing.JButton ResponseAcceptButton;
    private javax.swing.JPanel ResponseButtonsPanel;
    private javax.swing.JButton ResponseDeclineButton;
    private javax.swing.JPanel ResponsePanel;
    private javax.swing.JScrollPane ResponseScrollPane;
    private javax.swing.JTextArea ResponseTextArea;
    private javax.swing.JPanel RosterPanel;
    private javax.swing.JScrollPane RosterScrollPane;
    private my.ibmsdrh.RosterTableModel RosterTableModel;
    private javax.swing.JTextArea RosterTextArea;
    private javax.swing.JComboBox SelectHourCombo;
    private javax.swing.JComboBox SelectMinuteCombo;
    private javax.swing.JLabel StartDateLabel;
    private org.jdesktop.swingx.JXDatePicker StartDatePicker;
    private javax.swing.JLabel StartTimeLabel;
    private javax.swing.JComboBox StartingAreaCombo;
    private javax.swing.JComboBox StartingStopCombo;
    private javax.swing.JButton SubmitRequestButton;
    private javax.swing.JLabel ToAreaLabel;
    private javax.swing.JLabel ToBusStopLabel;
    private javax.swing.JButton ViewLiveDeparturesButton;
    private javax.swing.JButton ViewRosterButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
