#!/bin/bash
set -v
java CalendarHighlight 7 31 3
java CalendarHighlight 4 31 13
java CalendarHighlight 5 31 5
java CalendarHighlight 6 6 6
java CalendarHighlight 9 30 9
java CalendarHighlight 8 8 8
java CalendarHighlight 14 22 22
java CalendarHighlight 29 29 29
java CalendarHighlight 1 31 1
java CalendarHighlight 2 31 3
java CalendarHighlight 3 26 30
java CalendarHighlight 4 31 19
java CalendarHighlight 5 28 19
java CalendarHighlight 7 30 4
java CalendarHighlight 4 30 30



